### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by lemeow125** [lemeow125/EquipmentTracker-Backend#1]
*Assignees*
- Prince Dela Pena
- Marc Pacheco
- Sanchez Anthony
- Colendres Lorenzo

**ERD Tool Used**
draw.io

Make sure to commit the draw.io file to the [backend repository](https://github.com/lemeow125/EquipmentTracker-Backend). Any changes to the ERD should also be pushed to the repo

**Comment by Preyness** [comment]
Still subject to change ang ERD

**Comment by lemeow125** [comment]
QA: Needs revisions does not fully match requirements

**Comment by lemeow125** [comment]
Revisions made to match requirements. QA approved closing and marking as done


![Image](https://github.com/lemeow125/EquipmentTracker-Backend/assets/63192778/c127cd4c-d9fa-49bf-a4f9-dabc46e657ca)

**Comment by lemeow125** [comment]
Merged to master
